server:
  port: 8080

spring:
  datasource:
    sqles:
      url: jdbc:es://localhost:9200/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123
      driver-class-name: com.czcuestc.sqles.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        initial-size: 15 #连接池初始化大小
        min-idle: 20 #最小空闲连接数
        max-active: 30 #最大连接数
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static/,classpath:/templates/

logging:
  level:
    com:
      alibaba:
        druid=DEBUG:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
