spring:
  application:
    name: sqles
  profiles:
    active: dev #默认为开发环境
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: html/
      suffix: .html
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static/,classpath:/templates/